### ISSUE TITLE
No Problem, but a Request!

### ISSUE THREAD

**Issue by Sannosama** [jendave/augmented-reality-foundry#1]
This is amazing!  Thank you so much for integrating Augmented Reality into Foundry.
Would it be possible to make an option where the Table Rolls would just be for the GM?
I've tried everything I can think of, set Rolls to "Private GM Roll" and also "Blind GM Roll", the [Actually Private Messages](https://foundryvtt.com/packages/actually-private-rolls) module, and the rolls are always public.  I would LOVE to be able to keep these rolls private.  It feels like a magician revealing where the magic comes from on every roll, and the formatting kinda clogs up the Chat/Roll Log.
If there's any way to make an option for GM only rolls, I would absolutely love it!
Thanks again for your excellent work.  I can only imagine importing all of these tables and writing all that code!

**Comment by jendave** [comment]
Thanks for opening up the issue. I completely forgot to fix this. I have released 1.0.2 which uses the current Roll Mode instead of always being Public.

**Comment by Sannosama** [comment]
Thank you SO SO SO SO MUCH!
I didn't know how else to reach out.  It's working like a dream now!
I can't tell you how valuable of an asset this is that you've made.  Thank you, and excellent work!

**Comment by jendave** [comment]
Thanks! I am glad that you enjoy the module! Feel free to open more issues for any other requests you have. I am glad that people are using the module!
